[package]
name = "crabby"
version = "0.1.0"
authors = ["Th√©o Huchard <theo.huchard@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
regex = "1.3.9"

[lib]
path = "src/lib.rs"